### ISSUE TITLE
response_mode for apple provider

### ISSUE THREAD

**Issue by rarora20** [hybridauth/hybridauth#1241]
When I explicitly mention the response_mode for Apple as query or fragment, I receive errors. I think it is hardcoded. Can you confirm that? Thank you so much for this library! it is a boon 👍 
![Screen Shot 2020-09-22 at 2 03 07 PM](https://user-images.githubusercontent.com/71725664/93919972-7db15600-fcdc-11ea-8d1b-fab517e89504.png)

**Comment by ApacheEx** [comment]
yeah, currently it's hardcoded. And probably it makes sense to have it configurable...what do you think @sputnik73?

based on [docs](https://hybridauth.github.io/providers/apple.html):
>The current default value for response_mode is form_post (you can overrule it with query or fragment if you don’t have a scope defined). If a scope is defined, Apple always sends the code value as a POST request (Facebook and Google return the code as a query parameter).

**Comment by sputnik73** [comment]
I guess you are right, it should not be hardcoded. but users should be aware Apple overrules the setting if a scope is defined as far as I remember. I will have a look at it and fix it.

**Comment by rarora20** [comment]
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms

**Comment by sputnik73** [comment]
Thank you for the link. So only in case `scope` is explicitly defined as empty, other values than "form_post" are valid for`response_mode`. 

If you agree, I will only overrule `response_mode` with 'form_post' in line 103 if `scope` is not empty and in that case additionally trigger a warning with an explanation to the developer.

**Comment by rarora20** [comment]
Hello @sputnik73 ! Yes, Sir!! Thank you so much! 👍

**Comment by sputnik73** [comment]
Sorry for the delay! You wrote you set the `response_mode` for Apple _as query or fragment_. However  query parameters in the authorize url are not supported by hybridauth (this is not not a specific problem of the Apple provider class). Optional query parameters for the authorize url should be configured using `authorize_url_parameters`, not by modifying the url:

Only the default value for `response_mode` is hardcoded in Apple.php line 103. This parameter can be currently overruled by setting

```
'authorize_url_parameters' => [
  'response_mode' => 'query'
]
```

You cannot set the response_mode by  adding a query parameter to the `Apple::authorizeUrl` URL yourself, because in `OAuth2::getAuthorizeUrl()` currently no query parameters are expected (line 485):

```
$queryParams = http_build_query($this->AuthorizeUrlParameters, '', '&', $this->AuthorizeUrlParametersEncType);
return $this->authorizeUrl . '?' . $queryParams;
```

In my former post I suggested to modify the code and trigger a warning and modify `response_mode` if scope is defined.  However since `authorize_url_parameters` is only used in `getAuthorizeUrl()` this is not that easy. I think we should keep the code as it is, otherwise I could introduce a new configuration key `response_mode` (at the same level than `scope` and handle it in `Apple::initialize()`. Honestly I don't think it is worth the afford since for Apple `response_mode` will be _'form_post'_ most of the time, I guess other usecases are very rare. For that setting   'response_mode' in 'authorize_url_parameters' should be sufficiant?

**Comment by sputnik73** [comment]
@ApacheEx I think this issue can be closed since only the default value is hardcoded, but `response_mode` is configurable. Custom query parameters in `authorizeUrl` are not supported by `Oauth2`.

**Comment by ApacheEx** [comment]
got it, thx for checking
