### ISSUE TITLE
Deprecating API authentication through query parameters

### ISSUE THREAD

**Issue by a-samad** [hybridauth/hybridauth#1288]
## Question: Do the new version have Authorization HTTP header instead of using the `access_token` query parameter?

We have received and email from GitHub yesterday about the deprecation of API authentication through query parameters. 

We are using "hybridauth/hybridauth": "2.16.0".

Yes we will upgrade it to latest version but has the latest version that capability that is explained in [LINK](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/).

```
Using access_token as a query param

If you're currently making an API call similar to

curl "https://api.github.com/user/repos?access_token=my_access_token"

Instead, you should send the token in the header:

curl -H 'Authorization: token my_access_token' https://api.github.com/user/repos
```

**Comment by ApacheEx** [comment]
Hello, I'd say both HA versions v2 and v3 use Authorization HTTP header instead of Query parameter

**Comment by emsearcy** [comment]
At least for me, HybridAuth v2, using the GitHub.php provider from https://github.com/hybridauth/hybridauth/blob/v2/additional-providers/hybridauth-github/Providers/GitHub.php was using a query parameter.  I just worked around this by updating my GitHub.php to set `"Authorization: token {$this->api->access_token}"` (similar to how this was done in other providers).  I'm not providing a diff because my GitHub.php was already modified from upstream years ago, and I don't remember all the reasons why -- but hopefully that is helpful!

Make sure you are running latest v2 with "Add access_token only if it's not available in curl headers" in thirdparty/thirdparty/OAuth/OAuth2Client.php. Older versions of v2 always added access_token.

**Comment by ApacheEx** [comment]
yeah, you are right. It looks like some providers are using query parameter instead of header.
But it's only relevant for HA v2.

I'll close it as v2 is not maintained anymore.
