### ISSUE TITLE
Has anyone developed a Facebook provider for API v2.0?

### ISSUE THREAD

**Issue by finbarrmccarthy** [hybridauth/hybridauth#280]
My understanding is that support for the current V1.0 Facebook API will end in April 2015. Facebook have released v2.0 of their API earlier this year along with a new PHP sdk
https://github.com/facebook/facebook-php-sdk-v4
Just wondering if anyone has developed a hybridauth provider for this?

Thanks

**Comment by dtbaker** [comment]
Just started with Hybridauth and got this Facebook API error/notice:

![image](https://cloud.githubusercontent.com/assets/543073/5591956/06a7ba26-91ef-11e4-9b68-75b860fd99d8.png)

has anyone attempted using version 2.0 with hybridauth yet?

**Comment by dtbaker** [comment]
In base_facebook.php I added the v2.0/ suffix to these URLs and the warning went away. I'm not sure what will break, but login seems to work fine now:

```
public static $DOMAIN_MAP = array(
    'api'         => 'https://api.facebook.com/v2.0/',
    'api_video'   => 'https://api-video.facebook.com/',
    'api_read'    => 'https://api-read.facebook.com/',
    'graph'       => 'https://graph.facebook.com/v2.0/',
    'graph_video' => 'https://graph-video.facebook.com/',
    'www'         => 'https://www.facebook.com/v2.0/',
  );

**Comment by Shade-** [comment]
Facebook's SDK has been updated to support the new APIs but I don't really think they are cutting out the old SDK, which is the one hybridauth is using at the moment. I guess nobody has updated it yet because Facebook's new SDK is compatible with PHP 5.4 or newer whereas hybridauth has a 5.2< compatibility range. I don't even think it will drop compatibility with 5.2 and 5.3 in such a small amount of time, thus why your patch seems the best and might be proposed as a PR if it will be confirmed to be working.

**Comment by nazar-pc** [comment]
I think 5.4 is not a problem in 2015. Seriously, it was around for a long time and soon will be abandoned because 7.0 will release later this year. 5.4 is pretty sane requirement, all OSs are shipped now with either 5.5 or 5.6, but 5.4 for sure and there are not so many hosting providers that do not support 5.4 (and providers that didn't switch yet just because we, as developers, do not require them to).

Finally, 5.3 is insecure, think about users first.

**Comment by AdwinTrave** [comment]
HybridAuth v3-dev is PHP 5.4 and will most likely remain like that.

I will accept PR for third party providers that have higher requirements, but that will require inclusion of warning in the changelog and the new website/documentation.

**Comment by janhartigan** [comment]
@AdwinTrave is that branch relatively safe to use at this point?

**Comment by AdwinTrave** [comment]
It has implemented quiet a lot of things, but you will have to ask @miled about that.

**Comment by pbscreativeben** [comment]
Hi, can anyone please clarify (in simple terms if possible) the best course of action for upgrading ready for the Facebook API v1 30th April cut off date? Thanks! Ben

**Comment by bob-hinrichs** [comment]
"All Facebook-enabled apps will be automaticaly[sic] upgraded to API v2.0 on April 30, 2015." This is the text next to a large red exclamation point, referring to my Hybridauth app.  

"This means that if your app is using v1.0 calls on May 1st, 2015, calls will return behavior from v2.0 of the API. This is true even if we've released newer versions of the API."

"On February 26th, the admins, developers and testers associated with one or more of your apps will be defaulted to v2.0. This change won't affect your public users until April 30, 2015."  This seems to mean that if you are testing with one of these special accounts, your app will behave as though it is after April 30.

The 'Next Steps" indicate we should " Use the latest iOS, Android, PHP and Javascript SDKs. "  

The current version of the third party Facebook code in Hybridauth is not the latest, and the comments state Copyright 2011.

I'd like to second pbscreativeben's question above. (Assume we have the correct version of PHP)

**Comment by Shade-** [comment]
Hybridauth 3.x will be frameworks-independent, meaning that it will not matter if using provider-specific SDKs like Facebook's one. For 2.x, I'd say @dtbaker solution is the best out there as it updates the SDK with the corrent endpoints currently used by Facebook.

Nonetheless, the notice is shown just to developers, not to the actual users. You don't have to worry updating your Hybridauth copy on your own, as Facebook itself told you that after the scheduled deadline API calls will be defaulted to the new version of their endpoints (which is an automated procedure and should not affect the user experience in any visible way).

**Comment by bob-hinrichs** [comment]
Thanks for your answers here, Shade.
