### ISSUE TITLE
Authentication Failed Problem

### ISSUE THREAD

**Issue by kaanc** [hybridauth/hybridauth#334]
Hi,
I add hybridauth in my project but this return a error

For Facebook:
Fatal error: Uncaught exception 'Exception' with message 'Authentication failed! Facebook returned an invalid user id.'

For Twitter
Fatal error: Uncaught exception 'Exception' with message 'Authentification failed! Twitter returned an error. 

Line:
/Hybrid/Auth.php on line 147

**Comment by Shade-** [comment]
This issue is usually caused by a lack of resources, as both Facebook and Twitter requires port 443 to be opened. This is a useful function you can adapt on your needs to check if your server has the requirements for a specific provider (I have listed Facebook and Twitter as I know they require this, the others should not need port 443).

```php
function verify_port_check($provider = '')
{
	global $lang;
	
	$ssl_providers = array('Facebook', 'Twitter');
	
	// 3 seconds timeout to check for port 443
	$fp = @fsockopen('127.0.0.1', 443, $errno, $errstr, 3);
	
	// Port 443 is closed or blocked
	if (!$fp) {
	
		if ($provider and in_array($provider, $ssl_providers)) {
	
			flash_message($lang->sprintf($lang->mybridge_error_port_443_not_open, $provider), 'error');
			admin_redirect(MAINURL);
			
		}
		else {
			return false;
		}
	    
	}
	
	return true;

}```
