### ISSUE TITLE
Custom exceptions instead of just Exception

### ISSUE THREAD

**Issue by nazar-pc** [hybridauth/hybridauth#451]
I'm author of system that can work in asynchronous mode using ReactPHP, which means that all requests are processed in one process.
But because HybridAuth use `die` and `exit`, I've replaced them by `\ExitException`, which on system level is handled like `exit`, but didn't terminate process itself.
The problem is that HybridAuth catches any Exceptions, including my own `\ExitException`, which I wanted to catch on higher level.

Now there are basically two ways to solve this particular case, but in general both of them should be made:
* do not use `die` or `exit`
* replace `Exception` by something like `HybridAuthException`, so that you can catch only yours exceptions

Maybe there is some work in this direction in 3.0 branch (I'm not following its development currently), or we can even apply it for 2.x?
BTW, what are plans about 3.0 release and maybe some place to discuss it?

**Comment by miled** [comment]
I thought about that issue like a year ago or so and I decided to keep things that way, because many users -I think- might not be catching exceptions properly on the endpoint which may result on full path disclosures. Anyway, I'm open for the idea if someone is willing to work on a fix.

V3 however doesn't use as many dies as V2 (only once, when redirecting users iirc). The new version is a complete rewrite and it works slightly different than the previous one, but it still a semi functional product and at alpha stage. As of now, it has been entirely refactored and about 20 providers has been upgraded.

Unfortunately, V3 is *way* over schedule due to lack of time and or motivation on my part, but I'm planning to get back to work on the project in near future, and hopefully the new version can earn the community interest and contributions.

https://github.com/hybridauth/hybridauth/tree/3.0.0-Remake#todo
https://github.com/hybridauth/hybridauth/tree/3.0.0-Remake/src/Provider#list-of-done-adapters---untested-still

**Comment by nazar-pc** [comment]
> I think- might not be catching exceptions properly on the endpoint which may result on full path disclosures

Can you explain what did you meant here? I missed the point.
> V3 however doesn't use as many dies as V2 (only once, when redirecting users iirc)

I'd like to get rid of that as well, at least somehow optionally, because currently I'm maintaining [list of things](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/components/modules/HybridAuth/readme.md) I need to hack in HybridAuth on each update to work with my system, primarily for asynchronous mode.

> Unfortunately, V3 is way over schedule due to lack of time and or motivation on my part, but I'm planning to get back to work on the project in near future, and hopefully the new version can earn the community interest and contributions.

I know what you mean, I have few Open Source project to maintain as well. I'm still using HybridAuth and have no plans to move to something else at the moment, so I'm ready to help with code and something else (if you remember, that was actually me who warmed-up discussion and further development after more that a year of abandonment).

Unfortunately I'm not familiar with V3 codebase at all, it would be great to have some more specific TODO plus architecture overview to get familiar with how everything works (even upgrade guide is currently empty).

**Comment by miled** [comment]
> Can you explain what did you meant here? I missed the point.

I mean we should not simply replace every occurrence of [die](https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Endpoint.php#L116) with an [exception](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/components/modules/HybridAuth/Hybrid/Endpoint.php#L116), because that may reveal the path to webroot in case of an uncaught exception for some users.

> it would be great to have some more specific TODO plus architecture overview

Fair enough. I'll create a better tasks list and add more information about the new version., but I'd say that most of the work on library internals has been done and what remains at this stage is to 1) migrate as many providers as possible from v2 to v3, 2) unit testing, and 3) user documentation.

**Comment by nazar-pc** [comment]
> I mean we should not simply replace every occurrence of die with an exception, because that may reveal the path to webroot in case of an uncaught exception for some users.

Well, there still other Exceptions that should be accounted, since this exception with be thrown literally at each request it will be discovered immediately. Moreover, path disclosure doesn't cause significant harm if your code is fine, I'm having few websites whose source code is completely open and website structure is well known. If you'll catch `\Exception` just like it is currently shown in examples (for copy-pasters) it will be fine already. At least, would be sufficient to make it configurable with any default value.

I'll follow development and try to help with what I can to make 3.0 release out.

By the way, I see some stubs for tests, will you use PhpUnit, or it might be discussed?

I've tried PHPT tests format once and really like it.
Description: https://qa.php.net/phpt_details.php
PHP itself and HHVM as well are covered with this type of tests. They are slower that those you may write for PhpUnit, but they are extremely simple and allow to cover cases with `die`, uncaught exceptions and more that might be a problem otherwise.

**Comment by miled** [comment]
> By the way, I see some stubs for tests, will you use PhpUnit, or it might be discussed?

I can't write unit tests for my life, so I'm open for suggestions and I'd be grateful if someone more knowledgeable than me could help with that.

**Comment by nazar-pc** [comment]
I hate writing test as well, but at some point I need to know will my system build, install and at least show home page to user, so I did wrote some and plan to write more)
Look here for examples: https://github.com/php/php-src/tree/master/tests

**Comment by nazar-pc** [comment]
Custom exception seems to be already used in 3.0-Remake branch, so I'm closing this.
