### ISSUE TITLE
Branches organisation

### ISSUE THREAD

**Issue by Soullivaneuh** [hybridauth/hybridauth#463]
Just an interrogation about branches organisation.

Next release is actually on `3.0.0-Remake` and 2.4 on `master`, am I right?

What would be done when 3.0 will be stable? Merge it on master and abandon 2.x support?

I'm wondering because I'm surprised by the process. I'm used to see project on master for new version (e.g. 2.5, 3.0) and one branch per legacy tag (e.g. 2.3, 2.4 etc...) which works great with Packagist management.

You can see a typical example here: https://github.com/symfony/symfony

Thanks. :-)

**Comment by nazar-pc** [comment]
> Next release is actually on 3.0.0-Remake and 2.4 on master, am I right?

Mostly yes, I think potentially there might be some patch releases in 2.4.x

> I'm wondering because I'm surprised by the process. I'm used to see project on master for new version (e.g. 2.5, 3.0) and one branch per legacy tag (e.g. 2.3, 2.4 etc...) which works great with Packagist management.

That works for projects where one version smoothly succeeds another, but here 3.0.0-Remake is completely different rewrite of 2.x and not yet tested whether all providers work as expected, so it is not ready for master, but eventually be there I hope)

The problem here is that 2.4 just works, and no one knows for sure what providers work in 3.0) I think Facebook, Twitter and some other will be tested well anyway, but there are many others that should be confirmed to be working as well.

**Comment by miled** [comment]
@nazar-pc sum it up quite well. The idea is to get V3 to beta stage with the major providers tested and working before it can be merged into master branch.

**Comment by Soullivaneuh** [comment]
I understand well, thanks for clarification.

I'm wondering another question so: Where will be 2.4 branch when 3.0 will be on master? Is a new 2.x branch be pushed before merge?

**Comment by miled** [comment]
by then, v2 will have it's own and separate branch. understandably it will be maintenance only.
