### ISSUE TITLE
Use composer to load third party libs

### ISSUE THREAD

**Issue by hypeJunction** [hybridauth/hybridauth#478]
Motivation is to avoid the duplication of third party libraries. E.g. we already have Facebook SDK and OAuth libs in our app project, and it would be handy to let composer resolve those.

**Comment by ADmad** [comment]
:+1: for 3.0

**Comment by miled** [comment]
v3.0 only uses LightOpenID (2014) and OAuth PHP Library (2007) and they had to be included into the package because 1) they are now abandonware - I think, and I'm maintaining them along hybridauth. 2) I had to hack into their codes for minor improvements and fixes.

Anyway, I don't think we'll be using any external library other than those two.

https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/src/Thirdparty/readme.md

**Comment by ADmad** [comment]
On a related note have you considered using https://github.com/thephpleague/oauth2-client ?  Considering the fact that lot of providers are Oauth2 based it would considerably reduce the code you have to maintain.

**Comment by miled** [comment]
OAuth2 specifications are fairly easy to implement and doesn't need any external library. The real pain however is with OpenID and OAuth 1/1.0a, and that's what those libraries are for.

**Comment by ADmad** [comment]
Okay. By the way you could move the 3rdparty openid and oauth1 clients to separate repos of your own.

**Comment by PowerKiKi** [comment]
I believe this should be closed since there is nothing to load via composer according to @miled.
