### ISSUE TITLE
[3.0] Use Symfony OptionsResolver

### ISSUE THREAD

**Issue by Soullivaneuh** [hybridauth/hybridauth#485]
Symfony [OptionsResolver](http://symfony.com/doc/current/components/options_resolver.html) components is a powerful library for options management.

This can replace Abstract class properties by "defaults options" and the config property could be integrated on it too.

Interested? Could work a POV for demonstration.

**Comment by miled** [comment]
Good idea indeed, but I'd like to keep the external dependencies for hybridauth down to zero.

**Comment by Soullivaneuh** [comment]
@miled 

> I'd like to keep the external dependencies for hybridauth down to zero.

Can I have any explanation about why?

The power of composer is especially the possibility to use dependencies with ease and avoid to "reinvent the wheel".

This could be apply with option-resolver in this case, and buzz or guzzle http client for oauth request. This is not painful, instead, this will make a more reliable project because concentrated of principal task: OAuth protocols.

BTW in this case, this is not a really big dependency.

Are you neither interested for a POC?

Regards.

**Comment by miled** [comment]
> concentrated of principal task: OAuth protocols.

Hybridauth has always been a tiny but *monolithic* library and the implementation of OAuth protocols is just a component of the package and what it has to offer. Further more, I believe there's more than enough PHP OAuth libraries out there, and honestly I'm not interested in making Hybridauth into a yet another one of those.

I totally agree with you on the importance of Composer and that's why we are using Packagist repository as our main medium of distribution, however - as you may know, there's a lot of people who either can't or don't use Composer on their projects, and yes, for their sake I'm willing to reinvent the wheel - or to include it into the package if necessary.

> buzz or guzzle http client

V3 can (at least in theory as I haven't done any actual test yet) work with other http clients and different sessions storage like memcached or redis thought [dependency injection](https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/src/Adapter/AbstractAdapter.php#L86-L91), so no there's no issue there.

The idea is that Hybridauth should work out the box without any external dependency, and the end users are free to use other libraries to replace the default Hybridauth components if they wish so (i.e, logger, session, http client).

> Are you neither interested for a POC?

I did look at OptionsResolver, and as I said it's pretty good piece of code, but it has 1034 LOC and it weight 89,5 Ko (more than 1/3 or the entire Hybridauth 3 repo), so normally I'd pass, however if you think that it's worth it, then a proof of concept would be welcome, but no promises tho.

I hope that answer you questions.

**Comment by Soullivaneuh** [comment]
> there's a lot of people who either can't or don't use Composer on their projects, and yes, for their sake I'm willing to reinvent the wheel - or to include it into the package if necessary.

I understand this point of view (not users not using composer or as like tools :-P) despite the fact that this is reducing project scalability IMO.

> however if you think that it's worth it, then a proof of concept would be welcome, but no promises tho.

Will take a look if I got some time.

Thanks for answering. :+1:

**Comment by Soullivaneuh** [comment]
> I believe there's more than enough PHP OAuth libraries out there

Well, exactly, I can't find a reliable one. :-)
