### ISSUE TITLE
Debug info vs error

### ISSUE THREAD

**Issue by fcjurado** [hybridauth/hybridauth#573]
Starting from the error method on https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Logger.php:

How can I register only the "info" errors? If I set debug_mode to "info", It triggers the "error" method, not only the "info" method. An it prints all the $object, and it's unnecesary.

**Comment by AdwinTrave** [comment]
When debug mode set to info it prints the errors as well, that is correct, that is because error has higher importance. There currently is no way to get only info messages and there won't be any as it doesn't make sense to exclude errors which you need to know about in order to address them. You can modify the logger class if you wish to change that and remove a condition for errors to show when info is set. But I would strongly advise against that.
