### ISSUE TITLE
User profile request failed! Facebook returned an error: OAuthException: An active access token must be used to query information about the current user

### ISSUE THREAD

**Issue by LakshmanKatragadda** [hybridauth/hybridauth#592]
User profile request failed! Facebook returned an error: OAuthException: An active access token must be used to query information about the current user

**Comment by tchalvak** [comment]
This sounds unlikely to be a problem specific to hybridauth.  Try logging out of facebook entirely with your testing account and starting all parts of your login from scratch.  This message seems to describe an oauth token that was previously active with facebook that got timed out.  For example, if you partially authorized app access in facebook during development, but then didn't complete that authorization, and the app expects authorization to still continue but facebook has long since dropped the token.

**Comment by fonshua** [comment]
The same problem happens after I removed the app from Facebook. Although the error is from Facebook but HybridAuth needs to handle basic stuff like re-direct the user to login page. I haven't found any good solution for this.

**Comment by ApacheEx** [comment]
this should be fixed in newer version of HA. If not, please fill new issue.
