### ISSUE TITLE
Facebook-Connect and setUserStatus

### ISSUE THREAD

**Issue by webnologie** [hybridauth/hybridauth#745]
Hello I tried to write an post in Facebook..

```
	$config = dirname(__FILE__) . '/config.php';
	require_once( "Hybrid/Auth.php" );
	require_once( "Hybrid/Endpoint.php" );
	require_once('Hybrid/thirdparty/Facebook/autoload.php');

	// start login with facebook?
	if( isset( $_GET["login"] ) ){
		try{
			$hybridauth = new Hybrid_Auth( $config );

			$adapter = $hybridauth->authenticate( "facebook" );

$adapter->setUserStatus(
array(
"message" => "", // status or message content
"link" => "", // webpage link
"picture" => "", // a picture link
)
);
			
			
			$user_profile = $adapter->getUserProfile();
		}
		catch( Exception $e ){
			die( "<b>got an error!</b> " . $e->getMessage() ); 
		}
	}
```

but I always get the Error Message: "Provider does not support this feature."
Login works fine, but not the post.

Does anybody know a solution? 

Thank you

**Comment by drone-ah** [comment]
I have run into the same issue. As a temporary measure, I was able to revert to 2.7.0 to resolve this.

**Comment by birdy247** [comment]
I am also getting this message.  Is it a Facebook or HybirdAuth issue?

**Comment by driade** [comment]
Hello. I run into the same problem today, upgrading (ug) from 2.6 to 2.8 because of the deprecation of Facebook Api 2.3

I then realized the function setUserStatus doesn't exist anymore, as it was removed in #665 

If you need 2.8 (surely if you use Facebook API 2.3 from now on) you may use this snippet

```
$adapter->adapter->api->post('/me/feed', [
    'link'    => $link,
    'message' => $message,
], $adapter->adapter->token('access_token'));
```

Please be aware this snippet is valid if you want to post to someone's status

I'm going to see if I'm able to request a pull request for this.

**Comment by driade** [comment]
@annuh may help with this

**Comment by ApacheEx** [comment]
#753 works well for me.
