### ISSUE TITLE
Solved: logout Provider problem

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#818]
Is this a bug, a feature request or a question?
question

Give us a short description.
I want to delete/logout from one of the adapter or provider using the Hybrid_Auth class. and then I want to be redirect to i.e. twitter login page again.
I used $adapter->logout();
but the problem is that when I ask to redirect to the twitter login it assumes that I still loged in or it reads from the session.
My question how can I logout completely .

What version of Hybrid Auth does this relates to?
2.x-dev

Is this an issue with a provider? If yes, which one?
maybe

How can we replicate this issue?
logout issue

**Comment by ApacheEx** [comment]
of course, you won't be logged-out in twitter after logging out in HA. Because the session with Twitter is defined by a cookie owned by Twitter - you can't control it.

> but the problem is that when I ask to redirect to the twitter login it assumes that I still loged in or it reads from the session.

it reads from the Twitter cookies, not HA session. As solution, you can set `force_login` to `true` in your HA config. It will force the user to enter their credentials to ensure the correct user's account is authorized.

**Comment by RahulVerma989** [comment]
@engharb You to logout the user from your website and allow him to be able to choose another account the next time, can use getConnectedAdapters() method to get all the connected adapters of hybridauth and use foreach loop and call disconnect() method on each of the adapters. This way on logout all the connected adapters will get disconnected and user can choose another account on next login.
